### PR TITLE
[Hotfix] Fixed import and method used for version 0.0.2 (Import issue)

### PR DESCRIPTION
**Pull request by YanSte**
Hi @JorjMcKie,

I noticed some issues with the import. I've fixed them.

PS: Version 0.0.2 does not work without this fix.

Screenshot 2024-05-20 at 23 20 33

### CODE REVIEW

**Comment by xdave** [comment]
Just encountered this issue. Eagerly awaiting this fix. Thanks.

**Comment by YanSte** [comment]
I have this problem too, I will add it to this pull request as well.

`with error: name 'page' is not defined. Skipping...`

**Comment by xdave** [comment]
Interestingly, when I roll back to version 0.0.1, i get:
```
AttributeError: module 'pymupdf4llm' has no attribute 'to_markdown'
```

**Comment by YanSte** [comment]
Yes you have to remove fully.

**Comment by YanSte** [comment]
@JorjMcKie  some issue are on 

`pathname = save_image(page<<`

**Comment by YanSte** [comment]
@xdave I think I fixed all the issues. You can try with my branch

**Comment by xdave** [comment]
@YanSte  confirmed works

**Comment by YanSte** [comment]
Perfect thanks for your support, now let's wait for approval from @JorjMcKie.

**Review by JorjMcKie — APPROVED** [review]

**Comment by JorjMcKie** [comment]
Thank you!

**Comment by YanSte** [comment]
@JorjMcKie Just check save_image with None for the vec image I wasn't sure about.

**Pull request merged**
