### PR TITLE
Accept Path object in to_markdown function

### PR DESCRIPTION
**Pull request by dantetemplar**

### CODE REVIEW

**Comment by JorjMcKie** [comment]
Thank you for the contribution - much appreciated!
Actually, this is already supported implicitly: I just have to change the check of the parameter type.
The parameter is converted to a `pymupdf.Document` if not already one. And Document creation supports all imaginable alternatives - including `pathlib` Paths.
So all I need to do is something like this:
```python
if not isinstance(arg0, pymupdf.Document):
    doc=pymupdf.open(arg0)`
else:
    doc = arg0
```

**Comment by dantetemplar** [comment]
It seems to me that this approach will spoil the types a little. I think it's better to list all the suitable alternatives in the argument annotation. But in runtime itself, the if-else that you suggested fits well.

**Comment by dantetemplar** [comment]
In that case, should I implement it myself?

**Comment by JorjMcKie** [comment]
You can of course make that change immediately in you installation files.

**Comment by JorjMcKie** [comment]
As per the type checking mannerisms of these days:
I think we will reduce that a little, because the repo is still in its early development stages. So that parameter and similar one will just be `typing.Any` things for the time being.

**Comment by dantetemplar** [comment]
> As per the type checking mannerisms of these days: I think we will reduce that a little, because the repo is still in its early development stages. So that parameter and similar one will just be `typing.Any` things for the time being.

I understand you, but the pull request can still be accepted 🤗

**Comment by JorjMcKie** [comment]
Ok no problem actually - except, that we need your explicit agreement to our Contributor License Agreement.
We are making sure that all user contributions are backed by a well-defined legal foundation. So please add a comment somewhere here with the wording like "I have read and herewith accept the Artifex Contributor License Agreement."
That agreement can be downloaded / read from this site: https://artifex.com/contributor/

**Comment by dantetemplar** [comment]
> Ok no problem actually - except, that we need your explicit agreement to our Contributor License Agreement. We are making sure that all user contributions are backed by a well-defined legal foundation. So please add a comment somewhere here with the wording like "I have read and herewith accept the Artifex Contributor License Agreement." That agreement can be downloaded / read from this site: https://artifex.com/contributor/

I have read and herewith accept the Artifex Contributor License Agreement.

**Review by JorjMcKie — APPROVED** [review]

**Comment by JorjMcKie** [comment]
Thank you - Done!

**Pull request closed without merging**
